;             
CREATE USER IF NOT EXISTS SA SALT '3e31751006d5d3f6' HASH '0e17ef2314a071733dda6fc3af185e9cf93513989d80c3294b0cc0af82ef6659' ADMIN;           
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_62B8785E_EDC3_4B9C_B429_E1EB4FF281AB START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F745896D_4DFD_4FD0_88F0_996E98C751BC START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FF174B9E_6EA3_409B_8DF6_D3AAEE6CA832 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_09FCB79C_6D82_434F_98CD_BB3D33A4E6F9 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_06370EBB_57B5_4D13_BD1A_235890DCC0B9 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EC0F3FFA_94AE_4F46_863A_68817395A990 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8A89295E_F4F1_4664_888B_3EDCEE9AC1F6 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DA66B57F_EC31_414E_91A2_A37DA4A8D0D1 START WITH 1 BELONGS_TO_TABLE;    
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_93C84287_FC14_4351_B1F5_66D133E5C64D START WITH 1 BELONGS_TO_TABLE;    
CREATE MEMORY TABLE PUBLIC.BLOCK_USER(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_06370EBB_57B5_4D13_BD1A_235890DCC0B9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_06370EBB_57B5_4D13_BD1A_235890DCC0B9,
    BLOCK_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    NUMBER_FAIL INTEGER NOT NULL,
    USER_ID BIGINT NOT NULL
);          
ALTER TABLE PUBLIC.BLOCK_USER ADD CONSTRAINT PUBLIC.CONSTRAINT_6 PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BLOCK_USER;              
CREATE MEMORY TABLE PUBLIC.GROUPS(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_62B8785E_EDC3_4B9C_B429_E1EB4FF281AB) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_62B8785E_EDC3_4B9C_B429_E1EB4FF281AB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    NON_DEL TINYINT DEFAULT 1 NOT NULL
);      
ALTER TABLE PUBLIC.GROUPS ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUPS;  
CREATE MEMORY TABLE PUBLIC.ROLE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_93C84287_FC14_4351_B1F5_66D133E5C64D) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_93C84287_FC14_4351_B1F5_66D133E5C64D,
    NON_DEL TINYINT DEFAULT 1 NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    SCOPE VARCHAR(255) NOT NULL
);       
ALTER TABLE PUBLIC.ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;    
CREATE MEMORY TABLE PUBLIC.ROLE_GROUP(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_DA66B57F_EC31_414E_91A2_A37DA4A8D0D1) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_DA66B57F_EC31_414E_91A2_A37DA4A8D0D1,
    GROUP_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);     
ALTER TABLE PUBLIC.ROLE_GROUP ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE_GROUP;              
CREATE MEMORY TABLE PUBLIC.TOKEN_VERFICATION(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_EC0F3FFA_94AE_4F46_863A_68817395A990) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_EC0F3FFA_94AE_4F46_863A_68817395A990,
    EXPIRE_TIME TIMESTAMP NOT NULL,
    TOKEN_CODE VARCHAR(255) NOT NULL,
    TYPE INTEGER NOT NULL,
    USER_ID BIGINT NOT NULL
);     
ALTER TABLE PUBLIC.TOKEN_VERFICATION ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN_VERFICATION;       
CREATE MEMORY TABLE PUBLIC.USER(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F745896D_4DFD_4FD0_88F0_996E98C751BC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_F745896D_4DFD_4FD0_88F0_996E98C751BC,
    EMAIL VARCHAR(255) NOT NULL,
    ENABLE TINYINT DEFAULT 0 NOT NULL,
    NON_DEL TINYINT DEFAULT 1 NOT NULL,
    NON_LOCKED TINYINT DEFAULT 1 NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);    
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.CONSTRAINT_27 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;    
CREATE MEMORY TABLE PUBLIC.USER_DETAIL(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8A89295E_F4F1_4664_888B_3EDCEE9AC1F6) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8A89295E_F4F1_4664_888B_3EDCEE9AC1F6,
    ADDRESS VARCHAR(255) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FULLNAME VARCHAR(255) NOT NULL,
    GENDER TINYINT NOT NULL,
    PHONE VARCHAR(15) NOT NULL
);     
ALTER TABLE PUBLIC.USER_DETAIL ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_DETAIL;             
CREATE MEMORY TABLE PUBLIC.USER_GROUP(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_09FCB79C_6D82_434F_98CD_BB3D33A4E6F9) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_09FCB79C_6D82_434F_98CD_BB3D33A4E6F9,
    JOIN_DATE TIMESTAMP NOT NULL,
    GROUP_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);  
ALTER TABLE PUBLIC.USER_GROUP ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_GROUP;              
CREATE MEMORY TABLE PUBLIC.USER_ROLE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_FF174B9E_6EA3_409B_8DF6_D3AAEE6CA832) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_FF174B9E_6EA3_409B_8DF6_D3AAEE6CA832,
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL
);       
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.CONSTRAINT_BC PRIMARY KEY(ID);             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER_ROLE;               
ALTER TABLE PUBLIC.BLOCK_USER ADD CONSTRAINT PUBLIC.UK_O0SAR47XVD3DD91GPA7LVBB52 UNIQUE(USER_ID);             
ALTER TABLE PUBLIC.TOKEN_VERFICATION ADD CONSTRAINT PUBLIC.UK_ENH6B036JKSGBJ3G63H1BA5XQ UNIQUE(USER_ID);      
ALTER TABLE PUBLIC.USER ADD CONSTRAINT PUBLIC.UK_OB8KQYQQGMEFL0ACO34AKDTPE UNIQUE(EMAIL);     
ALTER TABLE PUBLIC.TOKEN_VERFICATION ADD CONSTRAINT PUBLIC.REF_USER_TOKEN FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;            
ALTER TABLE PUBLIC.USER_DETAIL ADD CONSTRAINT PUBLIC.FK3OBC7RUAT1J146P8DXFEI6DI FOREIGN KEY(ID) REFERENCES PUBLIC.USER(ID) NOCHECK;           
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.REF_USER_ROLE FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;     
ALTER TABLE PUBLIC.ROLE_GROUP ADD CONSTRAINT PUBLIC.REF_ROLE_GROUP FOREIGN KEY(ROLE_ID) REFERENCES PUBLIC.ROLE(ID) NOCHECK;   
ALTER TABLE PUBLIC.ROLE_GROUP ADD CONSTRAINT PUBLIC.REF_GROUP_ROLE FOREIGN KEY(GROUP_ID) REFERENCES PUBLIC.GROUPS(ID) NOCHECK;
ALTER TABLE PUBLIC.USER_GROUP ADD CONSTRAINT PUBLIC.REF_USER_GROUP FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;   
ALTER TABLE PUBLIC.USER_ROLE ADD CONSTRAINT PUBLIC.REF_ROLE_USER FOREIGN KEY(ROLE_ID) REFERENCES PUBLIC.ROLE(ID) NOCHECK;     
ALTER TABLE PUBLIC.BLOCK_USER ADD CONSTRAINT PUBLIC.REF_BLOCKUSER_USER FOREIGN KEY(USER_ID) REFERENCES PUBLIC.USER(ID) NOCHECK;               
ALTER TABLE PUBLIC.USER_GROUP ADD CONSTRAINT PUBLIC.REF_GROUP_USER FOREIGN KEY(GROUP_ID) REFERENCES PUBLIC.GROUPS(ID) NOCHECK;
